In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/preprocessed_news.csv")

df.head()

,title,text,subject,date,label,content,text_length,word_count,clean_content,title_length
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0,Ben Stein Calls Out 9th Circuit Court: Committ...,1118,185,ben stein calls th circuit court committed cou...,89
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1,U.S. President Donald Trump removed his chief ...,4876,779,president donald trump removed chief strategis...,55
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1,Puerto Rico Governor Ricardo Rossello said on ...,1913,314,puerto rico governor ricardo rossello said wed...,64
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0,OOPS: Trump Just Accidentally Confirmed He Le...,1334,195,oops trump just accidentally confirmed leaked ...,89
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1,Most U.S. presidential candidates go abroad to...,3193,539,presidential candidates abroad sharpen foreign...,55

In [3]:
df.columns.tolist()

['title',
 'text',
 'subject',
 'date',
 'label',
 'content',
 'text_length',
 'word_count',
 'clean_content',
 'title_length']

In [4]:
# Create title length feature

df["title_length"] = df["title"].str.len()

df[["title", "title_length"]].head()

                                               title  title_length
0  Ben Stein Calls Out 9th Circuit Court: Committ...            89
1  Trump drops Steve Bannon from National Securit...            55
2  Puerto Rico expects U.S. to lift Jones Act shi...            64
3   OOPS: Trump Just Accidentally Confirmed He Le...            89
4  Donald Trump heads for Scotland to reopen a go...            55

In [5]:
# Create title word count feature

df["title_word_count"] = df["title"].str.split().str.len()

df[["title", "title_length", "title_word_count"]].head()

,title,title_length,title_word_count
0,Ben Stein Calls Out 9th Circuit Court: Committ...,89,14
1,Trump drops Steve Bannon from National Securit...,55,8
2,Puerto Rico expects U.S. to lift Jones Act shi...,64,10
3,OOPS: Trump Just Accidentally Confirmed He Le...,89,12
4,Donald Trump heads for Scotland to reopen a go...,55,10

In [6]:
# Create clean content length feature

df["clean_content_length"] = df["clean_content"].str.len()

df[["clean_content", "clean_content_length"]].head()

                                       clean_content  clean_content_length
0  ben stein calls th circuit court committed cou...                 765.0
1  president donald trump removed chief strategis...                3322.0
2  puerto rico governor ricardo rossello said wed...                1165.0
3  oops trump just accidentally confirmed leaked ...                 888.0
4  presidential candidates abroad sharpen foreign...                2064.0

In [7]:
# Create clean content word count feature

df["clean_word_count"] = df["clean_content"].str.split().str.len()

df[["clean_content", "clean_content_length", "clean_word_count"]].head()

,clean_content,clean_content_length,clean_word_count
0,ben stein calls th circuit court committed cou...,765.0,106.0
1,president donald trump removed chief strategis...,3322.0,426.0
2,puerto rico governor ricardo rossello said wed...,1165.0,152.0
3,oops trump just accidentally confirmed leaked ...,888.0,104.0
4,presidential candidates abroad sharpen foreign...,2064.0,271.0

In [8]:
# Create title to content length ratio

df["title_content_ratio"] = (
    df["title_length"] /
    (df["clean_content_length"] + 1)
)

df[
    [
        "title_length",
        "clean_content_length",
        "title_content_ratio"
    ]
].head()

   title_length  clean_content_length  title_content_ratio
0            89                 765.0             0.116188
1            55                3322.0             0.016551
2            64                1165.0             0.054889
3            89                 888.0             0.100112
4            55                2064.0             0.026634

In [9]:
import string

# Create punctuation count feature

df["punctuation_count"] = df["content"].apply(
    lambda x: sum(char in string.punctuation for char in x)
)

df[["content", "punctuation_count"]].head()

                                             content  punctuation_count
0  Ben Stein Calls Out 9th Circuit Court: Committ...                 14
1  U.S. President Donald Trump removed his chief ...                 97
2  Puerto Rico Governor Ricardo Rossello said on ...                 43
3   OOPS: Trump Just Accidentally Confirmed He Le...                 34
4  Most U.S. presidential candidates go abroad to...                 63

In [10]:
# Create number count feature

df["number_count"] = df["content"].apply(
    lambda x: sum(char.isdigit() for char in x)
)

df[["content", "number_count"]].head()

                                             content  number_count
0  Ben Stein Calls Out 9th Circuit Court: Committ...             8
1  U.S. President Donald Trump removed his chief ...             6
2  Puerto Rico Governor Ricardo Rossello said on ...             0
3   OOPS: Trump Just Accidentally Confirmed He Le...            10
4  Most U.S. presidential candidates go abroad to...            24

In [11]:
# Create uppercase character count feature

df["uppercase_count"] = df["content"].apply(
    lambda x: sum(char.isupper() for char in x)
)

df[["content", "uppercase_count"]].head()

                                             content  uppercase_count
0  Ben Stein Calls Out 9th Circuit Court: Committ...              114
1  U.S. President Donald Trump removed his chief ...              207
2  Puerto Rico Governor Ricardo Rossello said on ...               57
3   OOPS: Trump Just Accidentally Confirmed He Le...               74
4  Most U.S. presidential candidates go abroad to...              116

In [12]:
# Create uppercase ratio feature

df["uppercase_ratio"] = (
    df["uppercase_count"] /
    (df["text_length"] + 1)
)

df[["text_length", "uppercase_count", "uppercase_ratio"]].head()

   text_length  uppercase_count  uppercase_ratio
0         1118              114         0.101877
1         4876              207         0.042444
2         1913               57         0.029781
3         1334               74         0.055431
4         3193              116         0.036318

In [13]:
# Create uppercase ratio feature

df["uppercase_ratio"] = (
    df["uppercase_count"] /
    (df["text_length"] + 1)
)

df[["text_length", "uppercase_count", "uppercase_ratio"]].head()

   text_length  uppercase_count  uppercase_ratio
0         1118              114         0.101877
1         4876              207         0.042444
2         1913               57         0.029781
3         1334               74         0.055431
4         3193              116         0.036318

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
# Initialize TF-IDF Vectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english",
    ngram_range=(1, 2)
)

In [16]:
# Check for missing values in clean_content
print("Missing values:", df["clean_content"].isnull().sum())

# Ensure all values are strings
df["clean_content"] = df["clean_content"].fillna("").astype(str)

# Check empty rows
print("Empty rows:", (df["clean_content"].str.strip() == "").sum())

Missing values: 9
Empty rows: 9

In [17]:
# Apply TF-IDF transformation

tfidf_matrix = tfidf.fit_transform(df["clean_content"])

print("TF-IDF transformation completed!")
print("Shape of TF-IDF matrix:", tfidf_matrix.shape)

TF-IDF transformation completed!
Shape of TF-IDF matrix: (44689, 5000)

In [18]:
# Remove rows with empty clean_content

df = df[df["clean_content"].str.strip() != ""].copy()

print("Dataset shape after removing empty rows:")
print(df.shape)

Dataset shape after removing empty rows:
(44680, 18)

In [19]:
# Apply TF-IDF again after removing empty rows

tfidf_matrix = tfidf.fit_transform(df["clean_content"])

print("Final TF-IDF matrix shape:", tfidf_matrix.shape)

Final TF-IDF matrix shape: (44680, 5000)

In [20]:
import os

# Create processed folder if it doesn't exist
os.makedirs("../data/processed", exist_ok=True)

# Save feature-engineered dataset
df.to_csv(
    "../data/processed/feature_engineered_news.csv",
    index=False
)

print("Feature-engineered dataset saved successfully!")
print("Location: ../data/processed/feature_engineered_news.csv")

Feature-engineered dataset saved successfully!
Location: ../data/processed/feature_engineered_news.csv

In [21]:
from scipy.sparse import save_npz

# Save TF-IDF matrix
save_npz(
    "../data/processed/tfidf_features.npz",
    tfidf_matrix
)

print("TF-IDF matrix saved successfully!")

TF-IDF matrix saved successfully!

In [22]:
df.columns.tolist()

['title',
 'text',
 'subject',
 'date',
 'label',
 'content',
 'text_length',
 'word_count',
 'clean_content',
 'title_length',
 'title_word_count',
 'clean_content_length',
 'clean_word_count',
 'title_content_ratio',
 'punctuation_count',
 'number_count',
 'uppercase_count',
 'uppercase_ratio']